sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8
install:
  - java -version && javac -version && mvn -version
before_script:
  - mvn dependency:resolve-plugins
script:
  - mvn clean install -Dgpg.skip=true -DskipTests
cache:
  directories:
  - $HOME/.m2
  - $HOME/.victims
