sudo: required
dist: trusty
addons:
  sonarcloud:
    organization: garethahealy-github
    token:
      secure: QKCjMyDNTrgQ4A/hFDPogF9WI8054qCiQt/x0AX5zTi+GfRIDwrWFvxd1i3fvtNY7eXcfgaSPp1ZLpKTS1yF/M2EmEGckZYWTFTpb98noJIXA0yS2JRrQdq9l5Vupju0B/hea7B7mBvBHODwCWl5Nx4f74AjNlsCGC/ldxQV/qk=
env:
  global:
  - secure: SQN61TF/FOlHrquGYhFfeLgmBvpb750/AWNZxbGe/0e9rNWZvLpNsToxbsrCkVuCBGx42Hzay2q+iGgO0Jp58Y1842AfTl22PTRm5ZGE/rY7eT0pIO6mbsE5K0Rbcpq18GqX18sce2V5XZbyvJXVxUwIQ4lj0WgLr8mXODtwVGk=
  - secure: jtXJ30JgO6tc3btHMXc3zgqsy8c55QlHOlZX8UduUl6uzj8lJPbmu1X1k9mROqliE2C68yZsCLESZaGdeHcfc1R/cly5YaiFaa85fOl2RPBomHSfiUO1LxvlLWO5t0EZozZ88uPJLuSe9sZBr50MuFRJpFm6G90DXGtTeAvfmpI=
  - secure: H5GOieoDpe/8K8VmqJDxebFS0GsBVs4yWbHQ6pu8Z64KbAyoXNaN7O9QhJLk5RkEejpN6wxKYA/7LBVP8k0cu2e3fVVcQDGq+h4pNvVSIykXyidDn4tBEcSi0/uC1aWhCmP9kPU2XhzL+o/CTB5wgiFxAXFikGOo/8h8mJIljFs=
  - secure: jee94h0oxCV8MeJSkweb9AZq9ICov7x0/pPH/TQmZ4nGb2lBjYzgKMgnPAGts7LNV1Ypa7llRdN2Oz+L15GETffTouXkLSdS7r9czYVAX32v5y8HDUlr1wfIyGKGzoip3XxbPQyFniE3gbjfZAyF4v4m8qrpIALgh5wLcNiQgog=
language: java
jdk:
- oraclejdk8
before_install:
- bash .travis/deploy-codesigning.sh
install:
- mvn -N io.takari:maven:wrapper -Dmaven=3.5.0
- java -version && javac -version && ./mvnw -version -B
before_script:
- ./mvnw com.offbytwo.maven.plugins:maven-dependency-plugin:3.1.1.MDEP568:go-offline -DexcludeGroupIds=com.github.dozermapper -B
script:
- ./mvnw clean install -B
- ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -B
deploy:
  provider: script
  script: bash .travis/deploy.sh
  skip_cleanup: true
cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache
